[workspace]
members = ["crates/cassiopeia-core"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "MPL-2.0"
repository = "https://github.com/haneoka-gakuen/cassiopeia"

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = "s"
panic = "abort"
strip = "symbols"
