[workspace]
members = [
    "crates/cassiopeia-cli",
    "crates/cassiopeia-core",
    "crates/cassiopeia-native",
    "crates/cassiopeia-wasm",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "MPL-2.0"
repository = "https://github.com/haneoka-gakuen/cassiopeia"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["float_roundtrip"] }
wasm-bindgen = "0.2.100"

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = "s"
panic = "abort"
strip = "symbols"
